name: "Code Tests"

on: [ push ]

jobs:
    implementation-tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - uses: actions/setup-go@v4
            name: Setup Go 1.20
            with:
              go-version: '1.20'

          - name: Install dependencies
            run: |
                go get github.com/fatih/color
                go get gopkg.in/yaml.v3

          - name: Run Tests
            run: go test -v ./...
